import React from 'react';
import styles from './HomePage.module.css';
import Image from 'next/image';
import InfoCard from './InfoCard/InfoCard';
import Offer from './Offer/Offer';
import FAQ from './FAQ/FAQ';

const HomePage = () => {
  return (
    <main >
      <div className="flex flex-col md:flex-row m-8 items-center">
      <div className="flex flex-col mx-5 flex-grow text-center md:text-left">
        <span className={`text-4xl md:text-5xl lg:text-6xl`}>
          Make <span className={styles.underline}>Smarter</span> Bets
        </span>
        <p className={`text-customBlue font-semibold my-10 text-xl md:text-2xl  ${styles.subHead}`}>
          Turn your sports knowledge into winning bets with data-driven insights!
        </p>
      </div>

      <div className="relative flex-shrink-0 w-full md:w-1/2 ">
        <div className="relative w-full h-64 md:h-80 ">
          <Image
            layout="fill"
            objectFit="contain"
            src="/lightbulb.png"
            alt="lightbulb"
          />
        </div>
      </div>
    </div>
      <div className={styles.infoCardsContainer}>
        <div className={styles.infoCard1}>
          <InfoCard
            title="AI Integration"
            description="Incorporates AI models that analyze data and predict reliable outcomes"
          />
        </div>
        <div className={styles.ladder1}></div>
        <div className={styles.infoCard2}>
          <InfoCard
            title="Real Time Data Analysis"
            description="Always Running. Always Reliable. Always Accurate"
          />
        </div>
        <div className={styles.ladder2}></div>
        <div className={styles.infoCard3}>
          <InfoCard
            title="Insightful Information"
            description="Make smarter bets based on statistics rather than speculation"
          />
        </div>
        <div className={styles.ladder1}></div>
        <div className={styles.infoCard4}>
          <InfoCard
            title="Results Driven"
            description="Many positive reviews from satisfied users"
          />
        </div>
      </div>
      <div className={`${styles.offersContainer} px-7 py-3`}>
        <div className={``}>
          <div className={`text-black text-center  font-bold text-5xl sm:text-7xl`}> Sharpen your edge </div>
          <div className={`text-black text-center my-3 font-semibold text-lg sm:text-2xl`}> Choose the plan that works best for you </div>
        </div>
        <div className={`flex justify-around`}>
          <div className={``}>
            <Offer
              title="Free Tier"
              description="Limited pick access-No account needed-Analytics and visual summary"
              price="$0.00"
              period=""
            />
          </div>
          <div className={``}>
            <Offer
              title="Monthly"
              description="Flexibility with payments-Full access to all picks"
              price="$9.99"
              period="/month"
            />
          </div>
          <div className={styles.offer3}>
            <Offer
              title="Yearly"
              description="Cheaper in the long run-Full access to all picks"
              price="$89.99"
              period="/year"
            />
          </div>
        </div>
      </div>
      <div className={`p-7 text-center flex flex-col`}>
        <span className={styles.faqTitle}>Frequently Asked Questions</span>
        <hr className={styles.faqLine}/>
        <FAQ question="What is sportwizzard?" answer="Sportwizzard is a sports betting platform that uses AI to provide data-driven insights to help users make smarter bets."/>
        <hr className={styles.faqLine}/>
        <FAQ question="What are the benefits of using sportwizzard?" answer="Sportwizzard provides users with AI-generated predictions, real-time data analysis, insightful information, and results-driven outcomes."/>
        <hr className={styles.faqLine}/>
        <FAQ question="How much does sportwizzard cost?" answer="Sportwizzard offers a free tier with limited pick access, as well as monthly and yearly plans for $9.99/month and $89.99/year, respectively."/>
        <hr className={styles.faqLine}/>
        <FAQ question="Should I tail the picks?" answer="While the picks are generated by AI, it is always recommended to do your own research and analysis before placing any bets."/>
        <hr className={styles.faqLine}/>
        <FAQ question="How do I cancel my subscription?" answer="You can cancel your subscription at any time by logging into your account and following the cancellation instructions."/>
      </div>
    </main>
  );
}

export default HomePage;